### ISSUE TITLE
对于setMoneyIn的疑问

### ISSUE THREAD

**Issue by BlackTrace** [NewEconoLab/neo-ns#5]
`public static bool setMoneyIn(byte[] txid)
        {
            var tx = getTxIn(txid);
            if (tx.from.Length == 0)
                return false;

            if (tx.to.AsBigInteger() == ExecutionEngine.ExecutingScriptHash.AsBigInteger())
            {
                var keytx = new byte[] { 0x12 }.Concat(txid);
                var n = Storage.Get(Storage.CurrentContext, keytx).AsBigInteger();
                if (n == 1)//这笔txid已经被用掉了
                    return false;
                //存錢
                var key = new byte[] { 0x11 }.Concat(tx.from);
                var money = Storage.Get(Storage.CurrentContext, key).AsBigInteger();
                money += tx.value;
                Storage.Put(Storage.CurrentContext, key, money);
                //記錄這個txid處理過了,只處理一次
                Storage.Put(Storage.CurrentContext, keytx, 1);
            }
            return false;
        }`
在nns_register_sell.cs中的setMoneyIn方法，不管是否成功的把gas转到这个合约账户，都返回false？

**Comment by BlackTrace** [comment]
都没人回复一下得吗？

**Comment by Jim8y** [comment]
源码不是这样的

**Comment by BlackTrace** [comment]
> 源码不是这样的

![image](https://user-images.githubusercontent.com/8064316/46239861-8f074680-c3d1-11e8-95c7-513a2a63e8bb.png)

**Comment by vikkkko** [comment]
这里确实少了一个return true

**Comment by BlackTrace** [comment]
> 这里确实少了一个return true

终于有人回复了，不容易啊。

**Comment by vikkkko** [comment]
> > 这里确实少了一个return true
> 
> 终于有人回复了，不容易啊。

不好意思  没收到邮件提醒  所以没及时回复

**Comment by BlackTrace** [comment]
gR$#7TTnWsXp!SWo

**Comment by QingmingZi** [comment]
OK，验证成功
